// Utility functions for report generation and download

export interface ReportData {
    generatedAt: string;
    generatedBy: {
        id: string;
        name: string;
        email: string;
    };
    dateRange: {
        startDate: string;
        endDate: string;
    };
    statistics: any;
    camps: any[];
    bloodRequests: any[];
    medicineRequests: any[];
}

/**
 * Convert report data to CSV format
 */
export const generateCSV = (data: ReportData): string => {
    const lines: string[] = [];

    // Header
    lines.push("GOVERNMENT COMPREHENSIVE REPORT");
    lines.push(`Generated At: ${new Date(data.generatedAt).toLocaleString()}`);
    lines.push(`Generated By: ${data.generatedBy.name} (${data.generatedBy.email})`);
    lines.push(`Date Range: ${data.dateRange.startDate} to ${data.dateRange.endDate}`);
    lines.push("");

    // Statistics
    lines.push("=== STATISTICS ===");
    lines.push(`Total Camps: ${data.statistics.camps.total} (Approved: ${data.statistics.camps.approved}, Rejected: ${data.statistics.camps.rejected}, Pending: ${data.statistics.camps.pending})`);
    lines.push(`Total Blood Requests: ${data.statistics.bloodRequests.total} (Fulfilled: ${data.statistics.bloodRequests.fulfilled}, Pending: ${data.statistics.bloodRequests.pending}, Cancelled: ${data.statistics.bloodRequests.cancelled})`);
    lines.push(`Total Medicine Requests: ${data.statistics.medicineRequests.total} (Fulfilled: ${data.statistics.medicineRequests.fulfilled}, Pending: ${data.statistics.medicineRequests.pending}, Cancelled: ${data.statistics.medicineRequests.cancelled})`);
    lines.push("");

    // Camps Section
    lines.push("=== CAMPS ===");
    lines.push("ID,Name,Organizer,Email,Phone,Date,Location,Status,Approval Status,Hospital Approval,Hospital Approver,Hospital Approved At,Hospital Rejection Reason,Government Approval,Government Approver,Government Approved At,Government Rejection Reason,Volunteers Needed,Registrations,Created At");

    data.camps.forEach(camp => {
        const row = [
            camp.id,
            `"${camp.name}"`,
            `"${camp.organizer}"`,
            camp.organizerEmail,
            camp.organizerPhone,
            new Date(camp.date).toLocaleDateString(),
            `"${camp.location}"`,
            camp.status,
            camp.approvalStatus,
            camp.hospitalApproval.status,
            `"${camp.hospitalApproval.approvedBy}"`,
            camp.hospitalApproval.approvedAt ? new Date(camp.hospitalApproval.approvedAt).toLocaleString() : "",
            `"${camp.hospitalApproval.rejectionReason}"`,
            camp.governmentApproval.status,
            `"${camp.governmentApproval.approvedBy}"`,
            camp.governmentApproval.approvedAt ? new Date(camp.governmentApproval.approvedAt).toLocaleString() : "",
            `"${camp.governmentApproval.rejectionReason}"`,
            camp.volunteersNeeded,
            camp.registrations,
            new Date(camp.createdAt).toLocaleString(),
        ];
        lines.push(row.join(","));
    });
    lines.push("");

    // Blood Requests Section
    lines.push("=== BLOOD REQUESTS ===");
    lines.push("ID,Requester,Email,Phone,Location,Blood Type,Quantity,Urgency,Status,Approved By,Notes,Created At,Updated At");

    data.bloodRequests.forEach(req => {
        const row = [
            req.id,
            `"${req.requester}"`,
            req.requesterEmail,
            req.requesterPhone,
            `"${req.requesterLocation}"`,
            req.bloodType,
            req.quantity,
            req.urgency,
            req.status,
            `"${req.approvedBy}"`,
            `"${req.notes}"`,
            new Date(req.createdAt).toLocaleString(),
            new Date(req.updatedAt).toLocaleString(),
        ];
        lines.push(row.join(","));
    });
    lines.push("");

    // Medicine Requests Section
    lines.push("=== MEDICINE REQUESTS ===");
    lines.push("ID,Requester,Email,Phone,Location,Medicine Name,Quantity,Urgency,Status,Approved By,Notes,Created At,Updated At");

    data.medicineRequests.forEach(req => {
        const row = [
            req.id,
            `"${req.requester}"`,
            req.requesterEmail,
            req.requesterPhone,
            `"${req.requesterLocation}"`,
            `"${req.medicineName}"`,
            req.quantity,
            req.urgency,
            req.status,
            `"${req.approvedBy}"`,
            `"${req.notes}"`,
            new Date(req.createdAt).toLocaleString(),
            new Date(req.updatedAt).toLocaleString(),
        ];
        lines.push(row.join(","));
    });

    return lines.join("\n");
};

/**
 * Download a file to the user's computer
 */
export const downloadFile = (content: string, filename: string, mimeType: string = "text/csv") => {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
};

/**
 * Format report data for display
 */
export const formatReportData = (data: ReportData) => {
    return {
        ...data,
        camps: data.camps.map(camp => ({
            ...camp,
            date: new Date(camp.date).toLocaleDateString(),
            createdAt: new Date(camp.createdAt).toLocaleString(),
            hospitalApproval: {
                ...camp.hospitalApproval,
                approvedAt: camp.hospitalApproval.approvedAt
                    ? new Date(camp.hospitalApproval.approvedAt).toLocaleString()
                    : null,
            },
            governmentApproval: {
                ...camp.governmentApproval,
                approvedAt: camp.governmentApproval.approvedAt
                    ? new Date(camp.governmentApproval.approvedAt).toLocaleString()
                    : null,
            },
        })),
        bloodRequests: data.bloodRequests.map(req => ({
            ...req,
            createdAt: new Date(req.createdAt).toLocaleString(),
            updatedAt: new Date(req.updatedAt).toLocaleString(),
        })),
        medicineRequests: data.medicineRequests.map(req => ({
            ...req,
            createdAt: new Date(req.createdAt).toLocaleString(),
            updatedAt: new Date(req.updatedAt).toLocaleString(),
        })),
    };
};

/**
 * Generate a filename for the report
 */
export const generateReportFilename = (prefix: string = "government_report"): string => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, -5);
    return `${prefix}_${timestamp}.csv`;
};
